### ISSUE TITLE
FireDac table descendant not exporting data

### ISSUE THREAD

**Issue by darianmiller** [darianmiller/dxIDEPackage_TDataSetVisualizer#2]
Reported by Tom Field

**Comment by darianmiller** [comment]
![Error Screenshot](https://raw.githubusercontent.com/darianmiller/dxWikiArtifacts/master/dxIDEPackage_TDataSetVisualizer/Issue2_FireDacError.png)

**Comment by tfield98** [comment]
Commenting as the naive user that I am, that error message wouldn't have been sufficient for me to know how to fix the problem.
